module ObjectTrackData {
    @topic
    struct Message {
        unsigned short sourceId;
        string sourceName;
        unsigned short trackId;
        string sensorTrackId;
        double latitude;
        double longitude;
        double bearing;
        double range;
        double altitude;
        double course;
        double speed;
        double verticalSpeed;
        long long time;
    };
};